version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: rustchain
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: rustchain
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgres://rustchain:securepass@db:5432/rustchain"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  pgdata:
